<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-B2220QC" ignored="2" name="Test(failed)" tests="2" failures="2" timestamp="2021-10-26T20:49:58 IST" time="0.246" errors="0">
  <testcase name="testB" time="0.023" classname="Demo.NewTestClass">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at Demo.NewTestClass.testB(NewTestClass.java:36)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- testB -->
  <testcase name="testC" time="0.007" classname="Demo.NewTestClass">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at Demo.NewTestClass.testC(NewTestClass.java:42)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- testC -->
  <testcase name="testA" time="0.0" classname="Demo.NewTestClass">
    <ignored/>
  </testcase> <!-- testA -->
  <testcase name="testD" time="0.0" classname="Demo.NewTestClass">
    <ignored/>
  </testcase> <!-- testD -->
</testsuite> <!-- Test(failed) -->
